services:
  app:
    image: alexluong/personal:alexluong.com-5.0
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - type: bind
        source: ${PWD}/data
        target: /pb_data
